
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Apr 19 14:46:07 CEST 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 9;
  public static final int CONST = 6;
  public static final int CASE = 27;
  public static final int LPAREN = 13;
  public static final int CONTINUE = 17;
  public static final int FOR = 22;
  public static final int MINUS = 30;
  public static final int CHARACTER = 48;
  public static final int RPAREN = 14;
  public static final int SEMICOLON = 5;
  public static final int AND = 31;
  public static final int LT = 37;
  public static final int OR = 28;
  public static final int BOOL = 47;
  public static final int COMMA = 8;
  public static final int INC = 23;
  public static final int DIV = 42;
  public static final int GEQ = 39;
  public static final int PLUS = 33;
  public static final int ASSIGN = 7;
  public static final int IF = 15;
  public static final int DOT = 29;
  public static final int EOF = 0;
  public static final int RETURN = 18;
  public static final int RBRACKET = 10;
  public static final int NEW = 34;
  public static final int error = 1;
  public static final int MUL = 41;
  public static final int NUMBER = 46;
  public static final int MOD = 43;
  public static final int NEQ = 36;
  public static final int IDENT = 45;
  public static final int BREAK = 16;
  public static final int VOID = 12;
  public static final int EQ = 35;
  public static final int SWITCH = 21;
  public static final int COLON = 26;
  public static final int ELSE = 44;
  public static final int LBRACE = 3;
  public static final int ENUM = 11;
  public static final int READ = 19;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int LEQ = 40;
  public static final int QUESTION = 25;
  public static final int DEC = 24;
  public static final int GT = 38;
  public static final int PRINT = 20;
  public static final int LENGTH = 32;
}

